Update to make compatible with homebrew for Mac on 10.13
Attempting to install via: 
brew install elmercsc/elmerfem/elmer

yields the following error:
Error: Calling 'depends_on :mpi' is disabled!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/elmercsc/homebrew-elmerfem/elmer.rb:22:in `<class:Elmer>'
Please report this to the elmercsc/elmerfem tap!
Or, even better, submit a PR to fix it!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/elmercsc/homebrew-elmerfem/issues

I believe this is the fix for this issue.

Thanks,
NSG